Smarthomeplaner/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# get the paths of every application
urlpatterns = [
    path("api/",include("api.urls")),
    path('smarthome/',include('smarthome.urls')),
    path('configurator/',include('configurator.urls')),
    path('userauth/',include("userauth.urls")),
    path('admin/', admin.site.urls),    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.viewsets import DeviceViewSet,VulnerabilityViewSet,DataProtectionInformationViewSet

router = routers.DefaultRouter()



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('devices/', DeviceViewSet.as_view()),
    path('vulnerability/', VulnerabilityViewSet.as_view()),    
    path('data-protection/', DataProtectionInformationViewSet.as_view()),    
]

configurator/urls.py
from django.urls import path,include
from django.views.generic import TemplateView

from . import views
app_name = "configurator"
urlpatterns = [
    path('', views.index, name='index'),
    path('getCanvas',views.getCanvas,name='getCanvas'),
    path('saveConfiguration',views.saveConfiguration,name='saveConfiguration'),
    path('configuration',views.configuration,name='smarthome_configurator'),
]

smarthome/urls.py
from django.urls import path,include
from django.views.generic import TemplateView

from . import views
app_name = "smarthome"
urlpatterns = [
    path('devices/<str:device_name>/', views.device_overview, name='device'),
    path('devices/', views.devices_overview, name='devices'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'nav_style.css' %}">
    {% block stylesheets %}
    {% endblock %}
    {% block javascripts %}
    {% endblock %}

    

    <title>{% block title %}Smarthomeplaner{% endblock %}</title>
</head>

<body>
    <div id="nav">
        {% block navbar %}
        {% include "nav.html" %}
        {% endblock %}
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/nav.html
<!-- http://www.w3bai.com/de/css/tryit.php?filename=trycss_navbar_vertical -->
{% load i18n %}


{% if user.is_authenticated %}
{% translate "Welcome" %} {{ user.email }}
<form method="post" action="{% url 'account_logout' %}" id="logout_form">
    {% csrf_token %}
      <input type="hidden" name="{{ redirect_field_name }}" value="{{ request.path }}      "/>
    <button class="STYLE_ME" type="submit">Logout</button>
  </form>
{% endif %}

<ul>
    <li><a href="{% url 'configurator:index' %}">{% translate "Configurator" %}</a></li>
    <li><a href="{% url 'smarthome:devices' %}">{% translate "Device Overview" %}</a></li>
    <li><a href="{% url 'configurator:smarthome_configurator' %}">{% translate "My Devices" %}</a></li>

    {% if not user.is_authenticated  %}
<li><a href="{% url 'account_login' %}">{% translate "Login" %}</a></li>
<li><a href="{% url 'account_signup' %}">{% translate "Register" %}</a></li>
{% endif %}

</ul>
  