Smarthomeplaner/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

# get the paths of every application
urlpatterns = [
    path("api/",include("api.urls")),
    path('smarthome/',include('smarthome.urls')),
    path('configurator/',include('configurator.urls')),
    path('userauth/',include("userauth.urls")),
    path('admin/', admin.site.urls),    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import include, path
from rest_framework import routers
from api.viewsets import DeviceViewSet,VulnerabilityViewSet,DataProtectionInformationViewSet

router = routers.DefaultRouter()



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('devices/', DeviceViewSet.as_view()),
    path('vulnerability/', VulnerabilityViewSet.as_view()),    
    path('data-protection/', DataProtectionInformationViewSet.as_view()),    
]

configurator/urls.py
from django.urls import path,include
from django.views.generic import TemplateView

from . import views
app_name = "configurator"
urlpatterns = [
    path('', views.index, name='index'),
    path('getCanvas',views.getCanvas,name='getCanvas'),
    path('saveConfiguration',views.saveConfiguration,name='saveConfiguration'),
    path('configuration',views.configuration,name='smarthome_configurator'),
]

smarthome/urls.py
from django.urls import path,include
from django.views.generic import TemplateView

from . import views
app_name = "smarthome"
urlpatterns = [
    path('devices/<str:device_name>/', views.device_overview, name='device'),
    path('devices/', views.devices_overview, name='devices'),
]

smarthome/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _ #translation
from users.models import AbstractBaseUser
from django.contrib.auth import settings
from users.models import CustomUser
from django.utils import timezone
from django.db.models.signals import m2m_changed, post_delete, pre_save
from django.dispatch import receiver
from django.template.loader import get_template,render_to_string
from django.template import Context
from django.core.mail import send_mass_mail



# Create your models here.


class Connector(models.Model):
    id = models.AutoField(primary_key=True)
    connector = models.CharField(max_length=30)

    def __str__(self):
        return self.connector

    class Meta:
        verbose_name = _("Connector")
        verbose_name_plural = _("Connectors")
        constraints = [models.UniqueConstraint(fields=["connector"],name="unique_connector")]

    # get the connector id e.g E14 --> ID=1
    @staticmethod
    def GetConnectorID(a_connector_name):
        return Connector.objects.filter(connector=a_connector_name).values_list("id",flat=True)[0]
    
    #get the connector object over name
    @staticmethod
    def GetConnector(a_connector_name):
        return Connector.objects.filter(connector=a_connector_name).get()
        

# which standards does the Product support?
class Standard(models.Model):
    standard = models.CharField(max_length=30,primary_key=True)
    def __str__(self):
        return self.standard

    class Meta:
        verbose_name = _("Standard")
        verbose_name_plural = _("Standard")


    #get the Standard object
    @staticmethod
    def GetStandard(a_standard):
        return Standard.objects.filter(standard=a_standard).get()



class Device(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    image = models.FileField(upload_to='Device')
    connector = models.ManyToManyField(Connector)
    standard = models.ManyToManyField(Standard,blank=True)
    manufacturer = models.CharField(max_length=200) 
    generation = models.CharField(max_length=10)
    compatible_device = models.ManyToManyField('self',verbose_name=_("Compatible with"),blank=True)
    
    class Device_Category(models.TextChoices):
        SMART_LIGHTNING = "Smart_Lightning", _("Smart_Lightning")
        SMART_LOCK = "Smart_Lock" , _("Smart_Lock")
        VIRTUAL_ASSISTANT = "Virtual_Assistant", _("Virtual_Assistant")

    category = models.CharField(
        max_length=20,
        choices=Device_Category.choices
    )

    class Meta:
        verbose_name = _("Device")
        verbose_name_plural = _("Devices")
        constraints = [models.UniqueConstraint(fields=["name","manufacturer","generation"],name="unique_device")]

    def __str__(self):
        return self.name +" " + self.manufacturer + "  V" + self.generation 


    @staticmethod
    def GetDevice(device_id):
        return Device.objects.filter(id=device_id).first()

    @staticmethod
    def GetCategories():
        choices_tuple = Device.Device_Category.choices
        choices = []
        for category in choices_tuple:
            choices.append(category[0])    
        return choices







class Firmware(models.Model):
    firmware_id = models.AutoField(primary_key=True) #todo rename to id
    compatibility_list = models.ManyToManyField(Device,verbose_name= _("Firmware Compatible with"))
    version_number = models.CharField(max_length=50,verbose_name= _("Versionnumber"))
    changelog = models.CharField(verbose_name=_("Changelog"), max_length=500)
    release_date = models.DateField(verbose_name=_("Release Date"),blank=True,null=True)

    class Meta:
        verbose_name = _("Firmware")
        verbose_name_plural = _("Firmwares")

    def __str__(self):
        firmwares = self.compatibility_list.all()
        manufacture = list(firmwares)[0].manufacturer
        devices = Device.objects.filter(firmware=self.firmware_id)
        device_names = ""

        for device in devices:
            device_names+=  str(device) + "," 
        return "Firmware Hersteller:"+manufacture +" Version: "+str(self.firmware_id)+ " supported devices:" + device_names



class Vulnerability(models.Model):
    id = models.AutoField(primary_key=True)
    device_id = models.ManyToManyField(Device,verbose_name= _("Vulnerability exploitable by:"))
    discovery = models.DateField(verbose_name= _("Vulnerability was found on:"))
    description = models.CharField(max_length=500,verbose_name= _("Description of the Vulnerability "))
    paper_url = models.URLField(max_length=500,verbose_name= _("URL to the Article to the Vulnerability"))
    patch_date = models.DateField(verbose_name= _("Vulnerability was patched on:"),null=True,blank=True)
    url_patch = models.URLField(max_length=500,verbose_name= _("URL to the Patch Article"),blank=True)

    class Vulnerability_Category(models.TextChoices):
        Firmware = "Firmware", _("Firmware")
        Physical = "Physical" , _("Physical")
        Others = "Others", _("Others")

    category = models.CharField(max_length=8,choices=Vulnerability_Category.choices)

    class Meta:
        verbose_name = _("Vulnerability")
        verbose_name_plural = _("Vulnerabilities")
    
    def __str__(self):
        return self.description 



# this signals sends the name 
@receiver(m2m_changed, sender=Vulnerability.device_id.through)
def notify_users(sender,action,pk_set,instance, **kwargs):
    email_sender = "smarthomeplaner@gmail.com"
    #check if a new vulnerability was added
    if(action == "post_add"):
        #maybe a closed vulnerability was added if so we dont want to send an email
        if(instance.patch_date is not None):
            device_entries = []
            user_mailingdict = {}
            messages = ()
            #pk_set is a list of ids which are vulnerable
            for device_id in pk_set:
                for entry in DeviceEntry.objects.filter(device=device_id):
                    user_email = str(entry.room.user)
                    name = entry.room.name
                    if ( user_email not in user_mailingdict):
                        # e.g user_mailingdict[user@aol.de]
                        user_mailingdict[user_email] = {}           
                        # add the roomname to the nested hashmap if necessary         
                    if not (user_mailingdict[user_email].__contains__(name)):
                        user_mailingdict[user_email][name] = [] 
                    user_mailingdict[user_email][name].append(entry)
            for user in user_mailingdict.keys():
                # the context holds every room with every device which is vulnerable
                context = {
                        'username': user,
                        "rooms" : user_mailingdict[user], 
                        "vulnerability": instance.description, 
                        }
                if (list(CustomUser.objects.filter(email=user).values_list("language_choice"))[0] == 'de-de'):
                    subject = "Neue Sicherheitslücke die dich betrifft"
                    email_text = render_to_string("smarthome/email_body_german.html",context)
                else:
                    subject = "A new Vulnerability added which concerns you "
                    email_text = render_to_string("smarthome/email_body_english.html",context)
                    #In order to send mass emails we create a tuple of messages which consists of
                #every subject is in the language of the user and now we can send every email to the users
                messages = messages + ((subject, email_text, email_sender, [user_email]),)
            send_mass_mail((messages))
        pass
            


class DataProtectionInformation(models.Model):
    id = models.AutoField(primary_key=True)
    device_id = models.ManyToManyField(Device,verbose_name= _("Privacy Concern affects the following devices:"))
    description = models.CharField(max_length=300)
    paper_url = models.URLField(max_length=500,verbose_name= _("URL to the Article to the Privacy Concern"))

    class Meta:
        verbose_name = _("Data Protection Information")
        verbose_name_plural = _("Data Protection Information")


    def __str__(self):
        return self.description 




class DeviceEntry(models.Model):
    id = models.AutoField(primary_key=True)
    room = models.ForeignKey("Room",on_delete=models.CASCADE)
    device = models.ForeignKey(Device,on_delete=models.CASCADE)
    connector = models.ForeignKey(Connector,on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        constraints = [models.UniqueConstraint(fields=["room","device","connector","quantity"],name="unique_entry")]
        verbose_name = _("Device Entry")
        verbose_name_plural = _("Device Entries")


    def __str__(self):
        return self.device.manufacturer +" "+ self.device.name +" "+ str(self.quantity) 


# device_list list of dict with {device_id,connector}
    @staticmethod
    def setEntries(a_room,device_list_dict):
        # get list of device_ids
        device_list = [a_dict["device_id"] for a_dict in device_list_dict]
        # get the unique connectors
        unique_dict_list = list(map(dict, set(tuple(sorted(sub.items())) for sub in device_list_dict))) 
        unique_connector_list = [a_dict["connector"] for a_dict in unique_dict_list]
        # loop variables
        l_connector = None
        for id in set(device_list):
            device_object = Device.GetDevice(id)
            for connector in unique_connector_list:
                l_connector = Connector.GetConnector(connector)
                quantity = DeviceEntry.GetDeviceQuantity(device_list_dict,id,connector)
                if(quantity == 0):
                    continue
                else:
                    if(DeviceEntry.exists(a_room,device_object,l_connector)):

smarthome/views.py
from django.shortcuts import render
from api.serializers import CanvasMap
from django.http import HttpResponse
from .models import Device
from django.http import Http404
from django.template import loader
from .models import Vulnerability,Device


# Create your views here.



def device_overview(request,device_name):
    try:
        
        device = Device.objects.get(name=device_name)
    except Device.DoesNotExist:
        raise Http404("Device does not exist")
    context = {
        "device" : device,
    }
    template = loader.get_template('smarthome/device_overview.html')
    return HttpResponse(template.render(context, request))





def devices_overview(request):
    devices = Device.objects.all()
    
    template = loader.get_template('smarthome/devices.html')
    context = {
        'devices': devices,
    }
    return HttpResponse(template.render(context, request))

smarthome/templates/smarthome/base_email.html
<html>
<body>
    
{% block salutation %}
Greetings {{username}}
{% endblock %}
{% block generic_information_text %}
You receive this Email, because a new Vulnerability is affecting one or more devices you are owning:
{% endblock %}





{% for room_name, table_data in rooms.items %} 
<strong>{{ room_name }}</strong>

{% for device_entry in table_data %} 

<p>{{ device_entry.device }} {{device_entry.connector}} </p>
{% endfor %}
{% endfor %}


{% block generic_additional_information %}
for more information please visit<a href="{% url 'configurator:smarthome_configurator' %}">us</a>
{% endblock %}



{% block generic_Vulnerability_text %}
Vulnerability description:
{% endblock %}
{{vulnerability}}


</body>
</html>

smarthome/templates/smarthome/device_overview.html
{% extends "base.html" %}
{% load i18n %}


{% block stylesheets %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'smarthome/style.css' %}">

{% endblock %}



{% block content %}


<div class="device_content"> 

    <h1>{{device}} ({{device.category}}) </h1>
    <div class = "connectors">
        <table>
            <tr>
            <th>{% translate "Connectors" %}</th>
        </tr>
            {% for connector in device.connector.all %}
            <tr><td>{{connector}}</td></tr> 
        {% endfor %}
        </table>    
    </div>

    <div class = "firmwares">
        <table>
            <caption>{% translate "Firmwares" %}</caption>
            <tr>
              <th>{% translate "Firmware Version" %}</th>
              <th>{% translate "Changelog" %}</th>
              <th>{% translate "Release Date" %}</th>
            </tr>

        {% for firmware in device.firmware_set.all %}
            <tr>
                <td>{{ firmware.version_number }}</td>
                <td>{{ firmware.changelog }}</td>
                {% if firmware.release_date %}
                <td>{{ firmware.release_date }}</td>
                {% else %}
                <td>-</td>
                {% endif %}
    
            </tr>
     
        {% endfor %}    
        
    </div>

    <div class = "description">
        {{ device.description }}
    </div>

    <div class = "vulnerabilities">
        <table>
            <caption>Vulnerabilities</caption>
            <tr>
              <th>{% translate "Discovered" %}</th>
              <th>{% translate "Description" %}</th>
              <th>{% translate "Link to the Paper" %}</th>
              <th>{% translate "Patch Date" %}</th>
              <th>{% translate "Link to the Patch Article" %}</th>
            </tr>
        {% for vulnerability in device.vulnerability_set.all %}
        {% if vulnerability.patch_date == None %}
        <tr class="red_row">
        {% else %}
        <tr>
        {% endif %}        
            {{vulnerability.patch_url}}
            <td>{{ vulnerability.discovery }}</td>
            <td>{{ vulnerability.description }}</td>
            <td><a href="{{vulnerability.paper_url}}">Paper</a></td>
            {% if vulnerability.patch_date %}
            <td>{{ vulnerability.patch_date }}</td>
            <td><a href="{{vulnerability.url_patch}}">Patch</td>
            {% else %}
            <td>-</td>
            <td>-</td>
            {% endif %}
        </tr>
        {% endfor %}    

    </div>

    <div class = "privacy_information">
        <table>
            <caption>{% translate "Privacy Information" %}</caption>
            <tr>
                <th>{% translate "Description" %}</th>
                <th>{% translate "Link to the Paper" %}</th>
              </tr>
        {% for privacy_concern in device.DataProtectionInformation_set.all %}
        <tr>
            <td>{{ privacy_concern.description }}</td>
            <td><a href="{{privacy_concern.paper_url}}">Paper</a></td>
        </tr>
        {% endfor %}    
    </div>
</div>

{% endblock %}

smarthome/templates/smarthome/devices.html
{% extends "base.html" %}
{% block content %}
    {% for device in devices %}
    <div id="container">
        <a href="{{ device.name }}/">{{ device.name }}</a>
    </div>
    
    {% endfor %}
    {% endblock %}

smarthome/templates/smarthome/email_body_english.html
{% extends "smarthome/base_email.html" %}

smarthome/templates/smarthome/email_body_german.html
{% extends "smarthome/base_email.html" %}

{% block salutation %}
Hallo {{username}},
{% endblock %}

{% block generic_information_text %}
Du erhältst diese Email, weil eine neue Sicherheitslücke in einen oder mehreren Geräten hinzugefügt wurde,
folgende Geräte in deinen Räumen sind betroffen:
{% endblock %}


{% block generic_additional_information %}
Für mehr Informationen <a href="{% url 'configurator:smarthome_configurator' %}">Klicke hier</a>
{% endblock %}


{% block generic_Vulnerability_text %}
Beschreibung der Schwachstelle
{% endblock %}